
spring:
  thymeleaf:
    # 关闭缓存，实时刷新，生产环境需要改为true
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  resources:
    static-locations: classpath:/static/
server:
  port: 11111
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: 12345678
    keyStoreType: PKCS12
    keyAlias: tomcat
  servlet:
    context-path: /KmsPackage/
kmsPackage:
  SecKMS: E:/三未信安/打包升级/updatefile/updatefile/SecKMS/
  KMIP: E:/三未信安/打包升级/updatefile/updatefile/KMIP/
  Rest: E:/三未信安/打包升级/updatefile/updatefile/Rest/RestFul/
  Standard: E:/三未信安/打包升级/updatefile/updatefile/Standard/
  HadoopKMS: E:/三未信安/打包升级/updatefile/updatefile/HadoopKMS/HadoopKMS/
  updateFilePath: E:/三未信安/打包升级/updatefile/updatefile/
  Soap: E:/updatefile/updatefile/Soap/Soap/
  version: E:/三未信安/打包升级/updatefile/updatefile/versioninfo.properties
  updateSign: E:/三未信安/打包升级/updatefile/
  packageWithoutSign: /opt/KmsPackage/updatefile/updatefile.zip
  packageWithSign: /opt/KmsPackage/updatefile.zip
  unPackageWithoutSign: E:/三未信安/打包升级/updatefile/
  unPackageWithSign: /opt/KmsPackage/
  sqlErrorLog: /opt/KmsPackage/log/sqlErrorLog.log
  template:
    Rest: /opt/KmsPackage/template/Rest.zip
    HadoopKMS: /opt/KmsPackage/template/HadoopKMS.zip
    otheroperation: /opt/KmsPackage/template/otheroperation.sh
